"""Backend-side helpers for short-lived E2E wrapped credential tokens."""

from __future__ import annotations

import base64
import binascii
import json
from datetime import UTC, datetime
from typing import Any

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


class WrappedCredentialError(ValueError):
    """Base error for malformed or invalid wrapped credential tokens."""


class WrappedCredentialExpiredError(WrappedCredentialError):
    """Raised when the wrapped credential token is expired."""


def unwrap_from_backend(
    token: str,
    *,
    key: bytes,
    now: datetime | None = None,
) -> str:
    """Decrypt a wrapped token generated by Flutter `E2eCrypto.wrapForBackend`.

    Supported payloads:
    1. Current Dart implementation: `ct` is a base64-encoded JSON string with
       fields `n` (nonce), `c` (cipher bytes), `m` (mac).
    2. Follow-up shape from task doc: `ct` is an object with `nonce`,
       `cipherBytes`, and `mac`.
    """
    if not token:
        raise WrappedCredentialError("Malformed wrap token")
    if len(key) != 32:
        raise WrappedCredentialError("Invalid E2E key length")

    payload = _decode_payload(token)
    expires_at = _parse_expires_at(payload)
    at = now.astimezone(UTC) if now is not None else datetime.now(UTC)
    if at > expires_at:
        raise WrappedCredentialExpiredError("Expired wrap token")

    nonce, cipher_bytes, mac = _parse_ciphertext(payload.get("ct"))
    try:
        plaintext_bytes = AESGCM(key).decrypt(nonce, cipher_bytes + mac, None)
    except Exception as exc:  # noqa: BLE001 - normalize error contract
        raise WrappedCredentialError("Credential unwrap failed") from exc

    try:
        return plaintext_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise WrappedCredentialError("Credential unwrap failed") from exc


def _decode_payload(token: str) -> dict[str, Any]:
    raw = _b64decode(token)
    try:
        decoded = json.loads(raw.decode("utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise WrappedCredentialError("Malformed wrap token") from exc
    if not isinstance(decoded, dict):
        raise WrappedCredentialError("Malformed wrap token")
    return decoded


def _parse_expires_at(payload: dict[str, Any]) -> datetime:
    value = payload.get("expiresAt")
    if not isinstance(value, int):
        raise WrappedCredentialError("Malformed wrap token")
    return datetime.fromtimestamp(value / 1000.0, tz=UTC)


def _parse_ciphertext(ct_value: Any) -> tuple[bytes, bytes, bytes]:
    if isinstance(ct_value, str):
        try:
            ct_obj = json.loads(_b64decode(ct_value).decode("utf-8"))
        except Exception as exc:  # noqa: BLE001
            raise WrappedCredentialError("Malformed wrap token") from exc
        if not isinstance(ct_obj, dict):
            raise WrappedCredentialError("Malformed wrap token")
        nonce = _read_b64_field(ct_obj, "n")
        cipher_bytes = _read_b64_field(ct_obj, "c")
        mac = _read_b64_field(ct_obj, "m")
        return nonce, cipher_bytes, mac

    if isinstance(ct_value, dict):
        nonce = _read_b64_field(ct_value, "nonce")
        cipher_bytes = _read_b64_field(ct_value, "cipherBytes")
        mac = _read_b64_field(ct_value, "mac")
        return nonce, cipher_bytes, mac

    raise WrappedCredentialError("Malformed wrap token")


def _read_b64_field(payload: dict[str, Any], key: str) -> bytes:
    value = payload.get(key)
    if not isinstance(value, str):
        raise WrappedCredentialError("Malformed wrap token")
    return _b64decode(value)


def _b64decode(value: str) -> bytes:
    try:
        return base64.b64decode(value.encode("ascii"), validate=True)
    except (UnicodeEncodeError, binascii.Error) as exc:
        raise WrappedCredentialError("Malformed wrap token") from exc
